metric_metrosim_both:
  _target_: gem.callbacks.metric.metric_metrosim_both.MetricMetrosimBoth
  vis_every_n_val: 5
  vis_max_sequences: 5
  vis_mode: "mesh"
  vis_max_frames: 150
  vis_out_dir: "out"
  vis_pyopengl_platform: "osmesa"
  vis_egl_device_id: null
  vis_mesh_backend: "auto"
